Sync 9.x to main
IBM/bamoe-docs pull request #68
Opened 2023-11-16 19:42 UTC by LightGuard

Hopefully there isn't anything we need to clean up.

2023-11-16 21:30 UTC, thiagoelg requested changes
Just a couple of changes regarding the `VERSION_OLD` and `VERSION_900` variables.

Also, we can change `KIE_TOOLS_COMMUNITY_VERSION` to 0.30.4.

Thanks for the changes @LightGuard!

2023-11-16 21:30 UTC, thiagoelg commented on introduction/release-notes/release-notes-9-0-0.adoc
> +Highlights, new features, removed components, and differences between {PRODUCT} {VERSION_OLD} and {VERSION}:
```suggestion
Highlights, new features, removed components, and differences between {PRODUCT} {VERSION_80} and {VERSION_900}:
```

2023-11-16 21:30 UTC, thiagoelg commented on partials/attributes.adoc
>  :VERSION_90X : 9.0.x
```suggestion
:VERSION: 9.0.1
:VERSION_900: 9.0.0
:VERSION_901: 9.0.1
:VERSION_90X : 9.0.x
```

2023-11-16 21:32 UTC, LightGuard commented
Suggestions accepted, thanks for the catch, @thiagoelg !

2023-11-16 21:37 UTC, thiagoelg approved these changes

2023-11-20 15:36 UTC, LightGuard commented
@porcelli @baldimir @thiagoelg @eduardocerqueira please review so we get get this merge to main and sync the work we did on `9.x` on `main`.

2023-11-27 21:06 UTC, LightGuard commented
@porcelli @baldimir @thiagoelg please review. (@thiagoelg I got your change request in)

2023-11-29 19:35 UTC, porcelli approved these changes
lgtm

2023-11-29 19:37 UTC, LightGuard commented
Perfect! Thank you everyone.

2023-11-29 19:37 UTC, merged