Fix table of supported libraries after the 9.0.1 release
IBM/bamoe-docs pull request #78
Opened 2024-01-22 21:41 UTC by martinweiler

We should add a table for each release in order to be precise on which library versions we support (as mandated by the bom).

@tiagobento is Kie Tools version 0.30.0 correct for both 9.0.0 and 9.0.1?

2024-01-22 23:41 UTC, LightGuard approved these changes

2024-01-30 19:25 UTC, LightGuard commented
@porcelli whenever you get a chance to take a look at this.

2024-02-12 20:15 UTC, LightGuard commented
@porcelli or @tiagobento how does this look?

2024-03-07 20:06 UTC, LightGuard commented
Bump for @porcelli and @tiagobento. Please review so we can merge.

2024-03-07 22:24 UTC, porcelli requested changes

2024-03-07 22:24 UTC, porcelli commented on introduction/supported-environments.adoc
> +|KIE Tools | 0.30.0
KIE Tools is not directly supported.

2024-03-07 22:24 UTC, porcelli commented on introduction/supported-environments.adoc
> +|Drools | 8.40.1.Final
it's not all libraries from those repos that we support. I think we have to articulate ore clear that we support a subset of libraries - and for those the versions are the ones listed here.

2024-04-12 19:47 UTC, LightGuard commented
@martinweiler Alex had some changes requested, I don't want to lose this.

2024-06-19 12:11 UTC, porcelli commented
this looks stale, should be merged or delete? @martinweiler @LightGuard

2024-06-19 13:42 UTC, martinweiler commented
I think it still makes sense to push this. The points @porcelli has raised are valid, but go beyond what this PR tried to achieve. The goal was to make it clear that 9.0.0 and 9.0.1 consist of different library versions.

2024-10-17 22:18 UTC, LightGuard commented
Still valid to merge?

2024-10-18 16:04 UTC, martinweiler commented
With the release of 9.1.x and the changes to the supported environments page in general, this is of lesser importance now.

2025-03-27 00:31 UTC, tiagobento commented
Closing as obsolete.

2025-03-27 00:31 UTC, closed without merging